// Copyright 2020 Lingfei Kong <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file.

// Code generated by "codegen -type=int /home/colin/workspace/golang/src/github.com/marmotedu/iam/internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to `github.com/marmotedu/errors`
func init() {
	register(ErrSuccess, 200, "OK")
	register(ErrUnauthorized, 200, "Unauthenticated")
	register(ErrInternalServerError, 500, "Internal server error")
	register(ErrBind, 200, "Error occurred while binding the request body to the struct")
	register(ErrExpiredToken, 200, "Token expired")
	register(ErrInvalidParams, 200, "Invalid Params")
	register(ErrDeny, 200, "Deny")
	register(ErrPageNotFound, 404, "Page not found")
	register(ErrDatabase, 500, "Database error")
}
