apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-account-full-access
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: full-access-role
subjects:
- kind: ServiceAccount
  name: default
